name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1
  - python=3.9
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - r-caret
  - r-ellipse
  - r-randomForest
  - r-kernlab
  - r-magrittr
  - pip
  - pip:
    - plotly 
    - pandas
    - matplotlib
    - scikit-learn
    - numpy
    - seaborn
    - statsmodels
    - scipy
    
